#!/bin/bash

set -e

java_home=$1
archeArtifactId=$2
testDir=${archeArtifactId//-} # escape '-' char because its not a valid java package
archeVersion=$3

mvnFlags="${testArchetypeMvn:=}"

export JAVA_HOME=$java_home

cd target

mvn archetype:generate $mvnFlags -DgroupId=com.abiquo.test -DartifactId=$testDir \
    -DarchetypeGroupId=com.abiquo -DarchetypeArtifactId=$archeArtifactId -DarchetypeVersion=$archeVersion \
    -DarchetypeCatalog=local -DinteractiveMode=false

cd $testDir
mvn $mvnFlags clean compile 

cd ../..
